[package]
name = "grepper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-terminal = "0.4.9"
r3bl_tuify = "0.1.4"
