# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the project as an HTML5 project.
    cmds:
      - lime test html5
    silent: true
