# https://taskfile.dev

version: "3"

vars:
  WASM: fib.wasm

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  build:
    cmds:
      - asc fibonacci.ts --outFile {{.WASM}} --optimize
