go: functions.c
	@echo "Building"
	@cc functions.c -o functions
	@echo
	@echo "Running"
	@echo "***************************************************************"
	@echo
	@./functions
	@echo
	@echo "***************************************************************"
	@echo 
	@echo Cleaning
	@rm functions

clean:
	rm functions
	
