# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  run:
    cmds:
      - go run useenvars
    silent: true
  withvar:
    cmds:
      - go run useenvars
    env:
      GREETING: Hey, there!
    silent: true
