# https://taskfile.dev

version: '3'

vars:
  BIN: bin/dcat.dart

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the 'dcat' app with 'README.md' as a parameter
    cmds:
      - dart run {{.BIN}} -n README.md
    silent: true
