# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists all the available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the application
    cmds:
      - go run ./src/main.go
    silent: true
  test:
    desc: Runs tests
    cmds:
      - go test ./src/...
    silent: true
