# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task --list-all
    silent: true
  lint:
    desc: Runs the golangci-lint and staticheck tools
    cmds:
      - golangci-lint run
      - staticcheck ./...
    silent: true
  server:
    desc: Starts the server component
    cmds:
      - go run ./cmd/web
    silent: true
    ignore_error: true
  testserver:
    desc: Tests the server component
    cmds:
      - go test -v ./cmd/web
    silent: true
  testpkg:
    desc: Tests the pkg components
    cmds:
      - go test -v ./pkg/...
    silent: true
  testservercoverage:
    desc: Tests the server component code coverage
    cmds:
      - go test -cover ./cmd/web
    silent: true
  test:
    desc: Runs all the tests (server/client/etc)
    cmds:
      - task: testserver
      - task: testpkg
    silent: true
  coverreportserver:
    desc: Shows test coverage report for the Server component
    cmds:
      - go test -coverprofile=coverage.out ./cmd/web
      - go tool cover -html=coverage.out
    silent: true
