# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Lists the available tasks.
    cmds:
      - task --list-all
      - echo
    silent: true
  report:
    desc: Reports various configured variable values.
    cmds:
      - echo "==================== REPORT ===================="
      - echo "Database name is   :" "{{.APP_DB_NAME}}"
      - echo "Database user is   :" "{{.APP_DB_USERNAME}}"
      - echo "Application port is:" "{{.APP_SERVER_PORT}}"      
      - echo
    silent: true
  run:
    desc: Runs the server, assuming the database is available as per the ENVARS.
    cmds:
      - go run .
    env:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: onepassword
      APP_DB_NAME: postgres
      APP_SERVER_PORT: 9000
    silent: true
  deleteddb:
    desc: Deletes the Docker TestDonkey image and volume. First stops TestDonkey.
    cmds:
      - docker stop TestDonkey
      - docker rm TestDonkey
      - docker volume prune --force
  startdb:
    desc: Starts the Test DB in a Docker instance
    cmds:
      - docker run --name TestDonkey -it -p 5432:5432 -e POSTGRES_DB=testgres -e POSTGRES_PASSWORD=testpassword -d postgres
  cleardb:
    desc: Clears the test database, but does not restart anything.
    cmds:
      - echo Todo
  test:
    desc: Runs tests against an active test DB instance in a Docker image.
    cmds:
      - go test -v
    env:
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: testpassword
      APP_DB_NAME: testgres
      APP_SERVER_PORT: 9000
    silent: true    
