# https://taskfile.dev

version: "3"

vars:
  PORT: 8080

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the server on port {{.PORT}}
    cmds:
      - PORT={{.PORT}} dart run bin/server.dart
    silent: true
  buildimage:
    desc: Builds the podman image
    cmds:
      - podman build -t my-dart-backend .
    silent: true
  runimage:
    desc: Runs the server image
    cmds:
      - podman run -d -p {{.PORT}}:{{.PORT}} my-dart-backend
    silent: false
