# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the app in the browser
    cmds:
      - flutter run -d chrome
    silent: true
