# https://taskfile.dev

version: "3"

vars:
  SRC_DIR: src
  TARGET_FILE: compiled.wasm

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task --list-all
    silent: true
  build:
    desc: Builds the wasm component with TinyGo
    cmds:
      - tinygo build -o static/{{.TARGET_FILE}} -target wasm ./{{.SRC_DIR}}/main.go
    silent: true
  buildGo:
    desc: Builds the wasm component with standard Go (to compare sizes)
    cmds:
      - GOOS=js GOARCH=wasm go build -ldflags="-s -w" -o static/withGo.wasm ./{{.SRC_DIR}}/main.go
    silent: true
  run:
    desc: Builds and runs the project
    cmds:
      - task: build
      - http-server ./static/ -p 9000 -o -c-1
    silent: true
