# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  run:
    cmds:
      - go run ./cmd/main.go
    silent: true
  test:
    cmds:
      - go test ./cmd/...
    silent: true
