# https://taskfile.dev

version: "3"

vars:
  PROJECT_FOLDER: web

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the webdev server
    cmds:
      - webdev serve {{.PROJECT_FOLDER}}:9000
    silent: true
  build:
    desc: Builds production code
    cmds:
      - webdev build --output {{.PROJECT_FOLDER}}:build
    silent: true
