# https://taskfile.dev

version: '3'

vars:
  GREETING: "| Academind Section 2 Project |"

tasks:
  default:
    desc: "Lists available tasks"
    cmds:
      - echo
      - echo "==============================="
      - echo "{{.GREETING}}"
      - echo "==============================="
      - echo 
      - task --list-all
      - echo
    silent: true

