# https://taskfile.dev

version: "3"

vars:
  SRC_DIR: src

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the `main.go` file
    cmds:
      - go run ./src/
    silent: true
  lint:
    desc: Runs the golangci-lint and staticcheck tools
    cmds:
      - golangci-lint run
      - staticcheck ./src/...
    silent: true
  test:
    desc: Tests the project.
    cmds:
      - go test -v ./src/.
    silent: true
  coverReport:
    desc: Shows test coverage report for the app
    cmds:
      - go test -coverprofile=coverage.out ./src/.
      - go tool cover -html=coverage.out
    silent: true
  updateDependencies:
    desc: Updates Go dependencies
    cmds:
      - go get -u ./...
    silent: true
