# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task --list-all
    silent: true
  server:
    desc: Starts the server component
    cmds:
      - go run ./cmd/web
    silent: true
    ignore_error: true
