/* Generated by           cobc 3.2.0 */
/* Generated from         hello.cbl */
/* Generated at           Oct 04 2024 13:58:07 */
/* GnuCOBOL build date    Oct 25 2023 15:01:45 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C hello.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {12, (cob_u8_ptr)"Hello, world", &a_1};

