# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  run:
    cmds:
      - flutter run -d chrome --web-renderer canvaskit
    silent: true
  build:
    cmds:
      - flutter build web --web-renderer canvaskit
    silent: true
