# https://taskfile.dev

version: '3'

vars:
  GREETING: "| Flame and Forge2D CodeLab |"

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - echo
      - echo "============================="
      - echo "{{.GREETING}}"
      - echo "============================="
      - echo 
      - task --list-all
      - echo
    silent: true
  run:
    desc: Runs the web app
    cmds:
      - flutter run -d chrome
    silent: true
  runandroid:
    desc: Runs the Android app
    cmds:
      - flutter run -d android
    silent: true
