[package]
name = "first_one"
version = "0.1.0"
edition = "2021"
authors = ["Ewald Horn"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
