# https://taskfile.dev

version: "3"

vars:
  OUT_DIR: static
  WASM_TARGET_FILE: mandelbrotter.wasm

tasks:
  default:
    desc: Lists available tasks
    cmds:
      - task --list-all
    silent: true
  updateDependencies:
    desc: Updates Go dependencies
    cmds:
      - go get -u ./...
    silent: true
  build:
    desc: Builds the project with TinyGo
    cmds:
      - tinygo build -o {{.OUT_DIR}}/{{.WASM_TARGET_FILE}} -opt=2 -no-debug -target wasm .
    silent: true
  updateWasmExec:
    desc: Updates the wasm_exec.js file
    cmds:
      - cp $(tinygo env TINYGOROOT)/targets/wasm_exec.js ./{{.OUT_DIR}}/wasm_exec_tiny.js
    silent: true
  run:
    desc: Builds and runs the project
    cmds:
      - task: build
      - http-server ./{{.OUT_DIR}}/ -p 9000 -c-1
    silent: true
