# https://taskfile.dev

version: "3"

vars:
  GO_WASM_DIR: "./public_golang/"

tasks:
  default:
    desc: Lists available commands
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the desktop app
    cmds:
      - go run .
    silent: true
  test:
    desc: Runs the Go tests
    cmds:
      - go test .
    silent: true
  build_wasm:
    desc: Builds the WASM target using Go
    cmds:
      - env GOOS=js GOARCH=wasm go build -o public_golang/wordleish.wasm .
    silent: true
  run_wasm:
    desc: Runs the Go wasm application
    dir: "{{.GO_WASM_DIR}}"
    cmds:
      - http-server . -p 9000 -o
