# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists available commands
    cmds:
      - task --list-all
    silent: true
  run:
    desc: Runs the desktop app
    cmds:
      - go run .
    silent: true
  test:
    desc: Runs the Go tests
    cmds:
      - go test .
    silent: true
