# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  run:
    cmds:
      - go test ./src/...
    silent: true
  test:
    cmds:
      - go test ./src/...
    silent: true
